### PR TITLE
fix: clean module file.

### PR DESCRIPTION
**Pull request by ldez**
remove unneeded indirect module reference.

### CODE REVIEW

**Comment by ldez** [comment]
@erickpintor friendly ping.

**Review by erickpintor — APPROVED** [review]
LGTM

**Comment by erickpintor** [comment]
BTW @ldez, I'm sorry for the late reply. As a side note, it looks like #126 also removes the unnecessary dependency.

**Review by vadimLF — APPROVED** [review]

**Review by vadimLF — COMMENTED** [review]
LGTM

**Comment by ldez** [comment]
Do you plan to merge this PR or I have to close in favor of #126?

**Comment by vadimLF** [comment]
> Do you plan to merge this PR or I have to close in favor of #126?

Let's close this one in favor of #126. Thank you, @ldez.

**Pull request closed without merging**
