### PR TITLE
DRV-310:  Revert StringConverter to pre v3

### PR DESCRIPTION
**Pull request by trevorsibanda**
Reverts StringConverter to pre-v3 output

### CODE REVIEW

**Review by erickpintor — COMMENTED** [review]
Did we miss the test coverage or are this string representations not tested?

**Comment by trevorsibanda** [comment]
Had missed them. Deleted and amended the commit

**Review by erickpintor — APPROVED** [review]
LGTM.

**Review by faunaee — APPROVED** [review]
LGTM 👍 
Thanks @trevorsibanda !

**Pull request merged**
