### PR TITLE
Docs for v4.0.0 release

### PR DESCRIPTION
**Pull request by vadimLF**
- ChangeLog file updates
- change module to v4

### CODE REVIEW

**Review by parkhomenko — APPROVED** [review]

**Review by n400 — APPROVED** [review]

**Comment by faunaee** [comment]
The CHANGELOG file mentions `Omitempty`, but the README file does not discuss how to use it. The README should include a brief discussion of what that's for, and some sample code showing how to use it.

**Review by n400 — CHANGES_REQUESTED** [review]
- Add support for document streaming
- Add support for 3rd party Auth
- Add support for Omitempty tag
- Add header for tracking runtime environments

**Comment by faunaee** [comment]
Note that the Go driver does not appear to include implementations for these functions:

* CurrentIdentity
* CurrentToken
* HasCurrentIdentity
* HasCurrentToken

Without these functions, the driver would not fully support for third-party auth.

**Comment by n400** [comment]
To address Ewan’s comment:

https://faunadb.atlassian.net/browse/DRV-599

**Comment by vadimLF** [comment]
All missed functions for 3rd party auth were added in https://github.com/fauna/faunadb-go/pull/139.
This PR was updated with go1.16.3 support (latest available).

**Comment by vadimLF** [comment]
This is duplicate with https://github.com/fauna/faunadb-go/pull/139

**Pull request closed without merging**
