### PR TITLE
Release v2.11.0

### PR DESCRIPTION
**Pull request by trevorsibanda**

### CODE REVIEW

**Comment by lolcoolkat** [comment]
When will this be released? :)

**Comment by lolcoolkat** [comment]
@trevorsibanda I noticed the `v2` release still has support for `Class` and `CreateClass`. Is this expected? I figured `v2` would deprecate this completely with the functions renamed to `Collection`. Any info is appreciated :)

**Comment by trevorsibanda** [comment]
@lolcoolkat For backwards compatibility, the functions have been deprecated but not removed. There is no timeline as of yet on when they will be officially removed.

**Comment by erickpintor** [comment]
What's the reason for v2? I don't recall any api breaking changes in 2.11.

**Pull request closed without merging**
